.TH "Global levels" 3 "Wed Jul 11 2012" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Global levels \- 
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBLVL_NONE\fP = 0"
.br
.ti -1c
.RI "const \fBLVL_USER\fP = 1"
.br
.ti -1c
.RI "const \fBLVL_ADMIN\fP = 2"
.br
.ti -1c
.RI "const \fBLVL_OWNER\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
