.TH "/Library/WebServer/Documents/fw-php/Watchperson.class.php" 3 "Thu Jul 12 2012" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Library/WebServer/Documents/fw-php/Watchperson.class.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWatchperson\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Matthew Howell smashuu@gmail.com 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0
.RE
.PP
.SH "LICENSE"
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details at http://www.gnu.org/copyleft/gpl.html
.SH "DESCRIPTION"
.PP
This class provides simple tools for handling login and authentication 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
